@startuml Core_modules

' style
skinparam monochrome true
skinparam shadowing false
skinparam classAttributeIconSize 0

interface ICPUBus {
    + MemRead(Address: uint64): byte
    + MemWrite(Address: uint64; Value: byte)
    + CodeRead(Address: uint64): byte
    + CodeWrite(Address: uint64; Value: byte)
    + IORead(Port: uint64): byte
    + IOWrite(Port: uint64; Value: byte)
}

class TCPU {
    # FBus: ICPUBus
    # FOnEvent: TCPUEventHandler
    # FName: string
    # FFamily: string
    # FArchitecture: TArchitecture
    # FBitWidth: byte
    # FAddressWidth: byte
    # FRunning: boolean
    # FHalted: boolean
    --
    + Create()
    + ConnectBus(Bus: ICPUBus)
    + {abstract} SetRegister(RegName: string; Value: qword)
    + {abstract} GetRegister(RegName: string): qword
    + {abstract} Reset()
    + {abstract} Step()
    + Run()
    + Stop()
}

class TBus {
    # FCodeMemory: TMemory
    # FDataMemory: TMemory
    # FIOPorts: TIOPort
    --
    + Create()
    + MemRead(Address: uint64): byte
    + MemWrite(Address: uint64; Value: byte)
    + AttachMemory(AMemory: TMemory)
    + AttachIOPorts(APorts: TIOPort)
    + Reset()
}

class TMemory {
    # FMaxRelAddress: qword
    # FSize: qword
    # FReadOnly: boolean
    --
    + Create(ASize: qword; AReadOnly: boolean)
    + {abstract} ReadByte(Address: qword): byte
    + {abstract} WriteByte(Address: qword; Value: byte)
    + {abstract} Reset()
}

class TIOPort {
    # FMaxRelAddress: qword
    # FSize: qword
    # FReadOnly: boolean
    --
    + Create(ASize: qword; AReadOnly: boolean)
    + {abstract} ReadPort(Port: qword): byte
    + {abstract} WritePort(Port: qword; Value: byte)
    + {abstract} Reset()
}

' Relations
TCPU -right-> ICPUBus : "has / uses"
TBus .up.|> ICPUBus : "implements"
TBus "1" *--> "0..2" TMemory : "manages FCode/FData"
TBus "1" *--> "0..1" TIOPort : "manages FIOPorts"

@enduml
