#!/usr/bin/bash
# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | createpic                                                                  |
# | Create UML diagram picture                                                 |
# +----------------------------------------------------------------------------+

format='pdf'

if command -v plantuml >/dev/null 2>&1; then
  for file in source/*.puml; do
    if [ -f "$file" ]; then
      y=$(basename "$file" .puml)
      for x in $format; do
        echo "$y.puml -> .$x"
        plantuml -t"$x" -o"../" "$file"
      done
    fi
  done
else
  echo "ERROR: The PlantUML is not installed."
fi
