#!/usr/bin/bash
# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | createpic                                                                  |
# | Create UML diagram picture                                                 |
# +----------------------------------------------------------------------------+

FORMAT='pdf'

# CHECK DEPENDENCY
chkdep() {
  if command -v $1 >/dev/null 2>&1;
  then
    return 0
  else
    echo -e "\nERROR: The '$1' is required to use the script."
    return 127
  fi
}

# check dependency
chkdep plantuml; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
# make diagrams
for file in source/*.puml; do
  if [ -f "$file" ]; then
    y=$(basename "$file" .puml)
    for x in $FORMAT; do
      echo "$y.puml -> .$x"
      plantuml -t"$x" -o"../" "$file"
    done
  fi
done

# If the output PDF is too large, use Ghostscript to reduce the size:
#
# gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen \
#    -dNOPAUSE -dQUIET -dBATCH -sOutputFile=smaller.pdf original.pdf
