# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | Makefile                                                                   |
# | Makefile for 64 bit Windows                                                |
# +----------------------------------------------------------------------------+

name = $(shell cmd /c dir /B /A:-D *.pas)
architecture = x86_64
os = win64
fpc = ppcx64
lcldir = c:\lazarus\lcl
outdir = .\lib\$(architecture)-$(os)
fpcargs = -T$(os) \
          -MObjFPC \
          -Scgi \
          -O1 \
          -v0 \
          -Fi../_inc \
          -Fi../corelab-parts/ \
          -Fu. \
          -Fu../_ext/* \
          -Fu../_ppu \
          -Fu../corelab-core/ \
          -Fu../corelab-parts/ \
          -Fu../corelab-plugins/ \
          -Fu$(lcldir)/../components/chmhelp/packages/help/ \
          -Fu$(lcldir)/../components/lazutils/lib/$(architecture)-$(os)/ \
          -Fu$(lcldir)/../components/turbopower_ipro/ \
          -Fu$(lcldir)/../components/synedit/ \
          -Fu$(lcldir)/../packager/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/win32/ \
          -Fu$(outdir) \
          -FE$(outdir) \
          -dLCL \
          -dLCLwin32 \
          -WG

all:
	@if not exist ..\_lib\nul md ..\_lib
	@if not exist $(outdir)\nul md $(outdir)
	@for %%x in ($(name)) do $(fpc) $(fpcargs) %%x
	@copy $(outdir)\*.dll ..\..\library

clean:
	@erase $(outdir)\*.*
