# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | Makefile                                                                   |
# | Makefile for 64 bit Windows                                                |
# +----------------------------------------------------------------------------+

name = corelab
architecture = x86_64
fpc = ppcx64
os = win64
lcldir = c:\lazarus\lcl
outdir = ..\_lib\$(architecture)-$(os)
fpcargs = -T$(os) \
          -MObjFPC \
          -Scgi \
          -O1 \
          -v0 \
          -Fu. \
          -Fu../_ext/* \
          -Fu../$(name)/core/ \
          -Fu$(lcldir)/../components/lazutils/lib/$(architecture)-$(os)/ \
          -Fu$(lcldir)/../components/synedit/ \
          -Fu$(lcldir)/../packager/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/win32/ \
          -Fu$(outdir) \
          -FE$(outdir) \
          -dLCL \
          -dLCLwin32 \
          -WG
project = $(shell dir /B /A:D | findstr /V /I "Makefile Makefile.w64")

all:
	@if not exist ..\_lib\nul md ..\_lib
	@if not exist $(outdir)\nul md $(outdir)
	  for %%x in ($(project)) do \
	    $(fpc) $(fpcargs) %%x/%%x.pas \
	@copy $(outdir)\*.dll.exe ..\..

clean:
	@erase $(outdir)\*.*
