#!/bin/bash
#
# create txz package on Linux
#

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

function createpackage()
{
find $NAME -exec touch {} +
chown -R root:root $NAME
makepkg -c y "../$NAME-$VERSION-$ARCH-$RELEASE.txz"
}

NAME="corelab"
RELEASE="1"
VERSION="0.1"

createpackage

NAME="corelab-plugins"
RELEASE="1"
VERSION="0.1"

createpackage
