#!/bin/bash
# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | md2html                                                                    |
# | .md to .html converter                                                     |
# +----------------------------------------------------------------------------+

FILES=`ls *.md`

# CHECK DEPENDENCY
chkdep() {
  if command -v $1 >/dev/null 2>&1;
  then
    return 0
  else
    echo -e "\nERROR: The '${1}' is required to use the script."
    return 127
  fi
}

# check dependency
chkdep pandoc; TOBE=$?; if [ $TOBE -ne 0 ]; then exit; fi
# convert files
for x in $FILES
do
  echo $x
  cat $x | grep -v '\# Core' | grep -v '\*\*Modular' | grep -v 'Copy' > temp.tmp
  TITLE=`cat temp.tmp | grep -F "## " | grep -v "###" | sed s/'## '/''/`
  pandoc temp.tmp -f markdown -t html -o output.html
  echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">' > $x.html
  echo '<html>' >> $x.html
  echo '<head>' >> $x.html
  echo '<title>CoreLAB - '$TITLE'</title>' >> $x.html
  echo '<meta http-equiv="content-language" content="en">' >> $x.html
  echo '<meta http-equiv="content-type" content="text/html; charset=utf-8" />' >> $x.html
  echo '</head>' >> $x.html
  echo '<body>' >> $x.html
  cat output.html >> $x.html
  echo '</body>' >> $x.html
  echo '</html>' >> $x.html
  rm -f output.html temp.tmp
done
