#!/bin/bash
# convert .md files to .html

files=`ls *.md`

for x in $files
do
  echo $x
  cat $x | grep -v '\# Core' | grep -v '\*\*Modular' | grep -v 'Copy' > temp.tmp
  TITLE=`cat temp.tmp | grep -F "## " | grep -v "###" | sed s/'## '/''/`
  pandoc temp.tmp -f markdown -t html -o output.html
  echo '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">' > $x.html
  echo '<html>' >> $x.html
  echo '<head>' >> $x.html
  echo '<title>CoreLAB - '$TITLE'</title>' >> $x.html
  echo '<meta http-equiv="content-language" content="en">' >> $x.html
  echo '<meta http-equiv="content-type" content="text/html; charset=utf-8" />' >> $x.html
  echo '</head>' >> $x.html
  echo '<body>' >> $x.html
  cat output.html >> $x.html
  echo '</body>' >> $x.html
  echo '</html>' >> $x.html
  rm -f output.html temp.tmp
done
