# $FreeBSD$

PORTNAME=	corelab
PORTVERSION=	0.1.0
CATEGORIES=	emulators
MAINTAINER=	pozsarzs@gmail.com
COMMENT=	Modular Processor Simulation Framework
USE_GITHUB=	yes
GH_ACCOUNT=	pozsarzs

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
