#!/bin/bash
# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | createvsix                                                                 |
# | Create .vsix file                                                          |
# +----------------------------------------------------------------------------+

# CHECK DEPENDENCY
chkdep() {
  if command -v $1 >/dev/null 2>&1;
  then
    return 0
  else
    echo -e "\nERROR: The '$1' is required to use the script."
    return 127
  fi
}

# check dependency
chkdep vsce; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
# create .vsix file
cd corelab-scriptembly
vsce package
mv *.vsix ..
cd ..
