# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | Makefile                                                                   |
# | Makefile for 32 bit Windows                                                |
# +----------------------------------------------------------------------------+

name = clprocessor
architecture = i386
fpc = ppc386
os = win32
lcldir = c:\lazarus\lcl
outdir = ..\..\_lib\$(architecture)-$(os)
fpcargs = -T$(os) \
          -MObjFPC \
          -Scgi \
          -O1 \
          -v0 \
          -Fi../_inc/ \
          -Fi../_inc/* \
          -Fu../_ext/* \
          -Fu../_ppu/* \
          -Fu../corelab-core/ \
          -Fu../corelab-parts/ \
          -Fu. \
          -Fu$(lcldir)/../components/lazutils/lib/$(architecture)-$(os)/ \
          -Fu$(lcldir)/../components/synedit/ \
          -Fu$(lcldir)/../packager/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/win32/ \
          -Fu$(outdir) \
          -FE$(outdir) \
          -dLCL \
          -dLCLwin32 \
          -WG

all:
	@if not exist ..\_lib\nul md ..\_lib
	@if not exist $(outdir)\nul md $(outdir)
	  for %%x in ($(project)) do \
	    $(fpc) $(fpcargs) %%x/%%x.pas \
	@copy $(outdir)\*.exe ..\..

clean:
	@erase $(outdir)\*.*
