# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | Makefile                                                                   |
# | Makefile for 32 bit Windows                                                |
# +----------------------------------------------------------------------------+

name = clprocessor
architecture = i386
os = win32
fpc = ppc386
lcldir = c:\lazarus\lcl
outdir = .\lib\$(architecture)-$(os)
fpcargs = -T$(os) \
          -MObjFPC \
          -Scgi \
          -O1 \
          -v0 \
          -Fi../_inc \
          -Fu. \
          -Fu../_ext/* \
          -Fu../_ppu \
          -Fu../corelab-core/ \
          -Fu../corelab-parts/ \
          -Fu../corelab-plugins/ \
          -Fu$(lcldir)/../components/chmhelp/packages/help/ \
          -Fu$(lcldir)/../components/lazutils/lib/$(architecture)-$(os)/ \
          -Fu$(lcldir)/../components/turbopower_ipro/ \
          -Fu$(lcldir)/../components/synedit/ \
          -Fu$(lcldir)/../packager/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/ \
          -Fu$(lcldir)/units/$(architecture)-$(os)/win32/ \
          -Fu$(outdir) \
          -FE$(outdir) \
          -dLCL \
          -dLCLwin32 \
          -dNOT_A_LIBRARY_BUT_A_UNIT \
          -WG

all:
	@if not exist .\lib\nul md .\_lib
	@if not exist $(outdir)\nul md $(outdir)
	@$(fpc) $(fpcargs) $(name).lpr
	@copy $(outdir)\$(name).exe ..\..

clean:
	@erase $(outdir)\*.*
