#!/bin/bash
# +----------------------------------------------------------------------------+
# | CoreLAB v0.1 - Modular Processor Simulation Framework                      |
# | Copyright (C) 2026 Pozsar Zsolt <pozsarzs@gmail.com>                       |
# | mkpackage                                                                  |
# | Makes .txz installer package                                               |
# +----------------------------------------------------------------------------+

DIR="CoreLAB"
NAM="corelab"
VER="0.1.0"
REL="1"
ARC="amd64"
PKG="${NAM}-${VER}-${ARC}-${ARC}"

# MAKE ZIP ARCHIVE
mkpkg_txz() {
  # check dependency
  chkdep makepkg; TOBE=$?; if [ $TOBE -ne 0 ]; then return; fi
  # make package
  rm --force "*.txz"
  find "$NAM" -exec touch {} +
  chown -R root:root "$NAM"
  cd "$NAM"
  makepkg -c y "../${PKG}.txz"
  if [ $? -eq 0 ]; then echo -e "\nFile ${PKG}.txz has been created."; fi
  cd ..
}

# CHECK DEPENDENCY
chkdep() {
  if command -v $1 >/dev/null 2>&1;
  then
    return 0
  else
    echo -e "\nERROR: The '${1}' is required to use the script."
    return 127
  fi
}

# MAIN
if [ ! -d "${NAM}/usr" ]
then
  mkdir --parents "$NAM"
  tar -xzf skeleton.tar.gz -C "$NAM"
  echo -e "\nAttention!"
  echo "~~~~~~~~~~"
  echo -e "I have unpacked the skeleton; first, fill it"\
       " with real files, then run this script again.\n"
  exit
fi

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

while true; do
    echo "Select type"
    echo "-----------------------"
    echo "1: create TXZ package"
    echo "-----------------------"
    echo "q: exit"
    read -p "Selected: " OPTION

    case $OPTION in
        1) mkpkg_txz;;
        q) break;;
        *) echo "Invalid selection.";;
    esac
    echo ""
done
