#!/bin/bash
#
# create deb package on Linux
#

if [ $# -eq 0 ]
then
  read -p "Architecture: " ARCH
else
  ARCH=$1
fi

function createpackage()
{
  find "${NAME}_${VERSION}-${RELEASE}_${ARCH}" -exec touch {} +
  fakeroot dpkg-deb --build "${NAME}_${VERSION}-${RELEASE}_${ARCH}" && lintian "${NAME}_${VERSION}-${RELEASE}_${ARCH}.deb"
}

NAME="corelab"
VERSION="0.1"
RELEASE='1'

createpackage
