#!/bin/bash
#
# create rpm package on Linux
#

if [ `whoami` != 'root' ]
then echo 'ERROR: You are not root!'; exit
fi

function createpackage()
{
  find BUILDROOT -exec touch {} +
  chown -R root:root BUILDROOT
  rpmbuild -ba --noclean "SPECS/$NAME-$VERSION-$RELEASE.spec"
  setarch amd64 rpmbuild -ba --noclean "SPECS/$NAME-$VERSION-$RELEASE.spec"
}

NAME="corelab"
RELEASE="1"
VERSION="0.1"

createpackage

NAME="corelab-plugins"
RELEASE="1"
VERSION="0.1"

createpackage
